package jacobfix.scoreprog;

public class StatProvider {
    /* It's got to be a HashMap with Integer keys and a special object for the value. */
    private static String[] descs = {
            "0", // 0
            "1",
            "Blocked Punt",
            "%d-Yard Run, First Down",
            "%d-Yard Pass, First Down",
            "Penalty, First Down",
            "3rd Down Attempt Converted",
            "3rd Down Attempt Failed",
            "4th Down Attempt Converted",
            "4th Down Attempt Failed",
            "%d-Yard Run", // 10
            "%d-Yard Run, TOUCHDOWN",
            "%d-Yard Run",
            "%d-Yard Run, TOUCHDOWN",
            "Incomplete Pass",
            "%d-Yard Pass",
            "%d-Yard Pass, TOUCHDOWN",
            "%d-Yard Pass",
            "%d-Yard Pass, TOUCHDOWN",
            "Interception",
            "Sack", // 20
            "%d-Yard Pass",
            "%d-Yard Pass, TOUCHDOWN",
            "%d-Yard Pass",
            "%d-Yard Pass, TOUCHDOWN",
            "Interception",
            "Interception, TOUCHDOWN",
            "Interception",
            "Interception, TOUCHDOWN",
            "Punt",
            "Punt", // 30
            "Punt",
            "Punt", // w/ Touchback
            "%d-Yard Punt Return",
            "%d-Yard Punt Return, TOUCHDOWN",
            "%d-Yard Punt Return",
            "%d-Yard Punt Return, TOUCHDOWN",
            "Punt, Out of Bounds",
            "38",
            "Punt, Fair Catch",
            "Punt, Touchback", // 40
            "Kickoff",
            "Kickoff",
            "Kickoff",
            "Kickoff, Touchback",
            "%d-Yard Kickoff Return",
            "%d-Yard Kickoff Return, TOUCHDOWN",
            "%d-Yard Kickoff Return",
            "%d-Yard Kickoff Return, TOUCHDOWN",
            "Kickoff, Out of Bounds",
            "Kickoff, Fair Catch", // 50
            "Kickoff, Touchback",
            "Fumble",
            "Fumble",
            "Fumble",
            "Own Fumble Recovery",
            "Own Fumble Recovery, TOUCHDOWN",
            "Own Fumble Recovery",
            "Own Fumble Recovery, TOUCHDOWN",
            "Opponent Fumble Recovery",
            "Opponent Fumble Recovery, TOUCHDOWN", // 60
            "Opponent Fumble Recovery",
            "Opponent Fumble Recovery, TOUCHDOWN",
            "%d-Yard Gain",
            "%d-Yard Gain, TOUCHDOWN",
            "65",
            "66",
            "67",
            "Timeout",
            "%d-Yard Field Goal No Good",
            "%d-Yard Field Goal Good",
            "%d-Yard Field Goal Blocked",
            "Extra Point Good",
            "Extra Point No Good",
            "Extra Point Blocked",
            "Two-Point Conversion Good",
            "Two-Point Conversion No Good",
            "Two-Point Conversion Good",
            "Two-Point Conversion No Good",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "Penalty",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
            "100",
            "101",
            "102",
            "103",
            "104",
            "105",
            "106",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
            "113",
            "114",
            "115",
            "116",
            "117",
            "118",
            "119",
            "120",
    };

    private static boolean[] includeYardage = {
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false
    };

    public static String getTitle(int index) {
        return descs[index];
    }

    public static boolean includeYardage(int index) {
        // return includeYardage[index];
        return true;
    }
}
